pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('book-manager-backend') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('book-manager-backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('book-manager-backend') {
                    sh 'docker build -t book-manager-backend:latest .'
                }
            }
        }

        stage('Push Image to Registry') {
            steps {
                echo 'Push Docker image to Azure Container Registry (ACR)'
            }
        }

        stage('Deploy to Azure App Service') {
            steps {
                echo 'Update Azure App Service to use latest Docker image'
            }
        }
    }
}
